# Generated by Django 5.1.1 on 2024-09-16 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="table_of_content",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="blog.tableofcontent"
            ),
        ),
    ]
