# Generated by Django 5.1.1 on 2024-09-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_table_of_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="dislikes",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="likes",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="views",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
