# Generated by Django 5.1.1 on 2024-09-16 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_dislikes_alter_blogpost_likes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="table_of_content",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.tableofcontent",
            ),
        ),
    ]
