# Generated by Django 5.1.1 on 2024-09-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_blogpost_likes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="reaction_count",
        ),
    ]
