# Generated by Django 5.1.1 on 2024-09-16 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_remove_blogpost_dislikes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="reactions",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_post",
                to="blog.reaction",
            ),
        ),
    ]
