# Generated by Django 5.1.1 on 2024-09-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_reaction_user_that_reacted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="reactions",
        ),
        migrations.AddField(
            model_name="reaction",
            name="blog_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reaction",
                to="blog.blogpost",
            ),
        ),
    ]
