# Generated by Django 5.1.1 on 2024-09-17 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_remove_blogpost_reactions_reaction_blog_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="comments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_post",
                to="blog.comment",
            ),
        ),
    ]
